[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "sandlersteam"
version = "0.0.1"
authors = [
  { name="Cameron F Abrams", email="cfa22@drexel.edu" },
]
description = "A Python interface to the steam tables in Stan Sandler's Thermodynamics book (5e)"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "numpy",
    "pandas",
    "scipy"
]
[tool.pytest.ini_options]
log_cli = true
